services:
  # Discord Bot Service
  - type: web
    name: discord-rolebot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python rolebot.py
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: PORT
        value: 10000
    autoDeploy: true
    healthCheckPath: /health
    healthCheckTimeout: 5 